x-service-provisioning-base: &provisioning-base
  build:
    args:
      GID: ${GID:-0}
      UID: ${UID:-0}
    context: Dockerfile.d/provisioning
  command:
    - zsh
    - -ic
    - |
      rm -rf /tmp/provisioning/.terraform.d
      /project/scripts/provisioning.init-with-azure.sh
      sleep infinity
  environment:
    - CURRENT_ENV_NAME
    - PROJECT_UNIQUE_ID
    - AZURE_DEFAULT_LOCATION
    - ARM_CLIENT_ID
    - ARM_CLIENT_SECRET
    - ARM_SUBSCRIPTION_ID
    - ARM_TENANT_ID
    - TF_DATA_DIR=/tmp/provisioning/.terraform.d/
    - TF_VAR_allowed_ipaddr_list=${TF_VAR_allowed_ipaddr_list}
    - TF_VAR_azure_default_location=${AZURE_DEFAULT_LOCATION}
    - TF_VAR_arm_subscription_id_another
    - TF_VAR_project_unique_id=${PROJECT_UNIQUE_ID}
  user: "${UID:-0}:${GID:-0}"
  volumes:
    - provisioning-home-developer:/home/developer
    - provisioning-home-root:/root # for macOS
    - ~/.ssh:/home/developer/.ssh:ro
    - ~/.ssh:/root/.ssh:ro # for macOS
    - ./config:/project/config
    - ./provisioning:/project/workspace
    - ./scripts:/project/scripts
    - ./tmp/provisioning:/tmp/provisioning
  working_dir: /project/workspace

services:
  provisioning:
    <<: *provisioning-base
version: "3.8"
volumes:
  provisioning-home-developer:
    driver: local
  provisioning-home-root:
    driver: local
